export const appInfo = {
  url: '',
  name: '',
  image: '',
  title: '',
  phone: '',
  email: '',
  topic: '',
  owner: '',
  domain: '',
  author: '',
  twitter: '',
  subject: '',
  summary: '',
  keyWords: '',
  category: '',
  abstract: '',
  subtitle: '',
  lang: 'pt-br',
  copyright: '',
  description: '',
  primaryColor: 'colors.primary'
}
